stages:
  - deploy

push_to_github:
  stage: deploy
  tags:
    - gitlab-to-github
  script:
    - whoami
    - cd /tmp
    - git clone --bare https://code.ihep.ac.cn/hepai/hai-gradio-auth-example.git
    - cd hai-gradio-auth-example.git
    - https_proxy=http://localhost:8118 git push --mirror https://github.com/open-hepai/hai-gradio-auth-example.git
    - cd ..
    - rm -rf hai-gradio-auth-example.git
  only:
    - main
    